logging:
  level:
    com.githnub.jactor: debug

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 1099
  servlet:
    context-path: "/jactor-persistence"

spring:
  datasource:
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jactor
  jpa:
    hibernate:
      ddl-auto: validate
