name: ci-maven
author: jactor-rises
description: A maven build using an offical maven image

inputs:
  workpath:
    description: File path to the folder containing the pom.xml
    required: true
  artifact:
    description: Name of the artifact beeing build
    required: false
    default: 'jactor-persistence'

using: 'docker'
image: 'docker://maven:3.6.2-jdk-12'

runs: |
  env
  docker run -it -rm --name "${INPUT_ARTIFACT}" -v "${INPUT_WORKPATH}":/usr/src/maven maven:3.6.2-jdk-12 mvn package
