name: build maven artifact
on: push

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build maven artifact

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          cache: maven
          distribution: temurin
          java-version: 17
      - uses: jactor-rises/actions/maven-verify-dependencies@v2-maven-verify-dependencies
      - run: mvn -B install -e
        if: github.ref != 'refs/heads/main'
      - run: mvn -B install -DskipTests
        if: github.ref == 'refs/heads/main'

  deploy:
    needs: build
    if: github.ref == 'refs/heads/feature/tag-snapshot'
    uses: jactor-rises/jactor-shared/.github/workflows/prepare-deploy.yaml@feature/tag-snapshot
