name: continious integration
on:
  push:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build and test with maven

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 13
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Debug
        run: env
      - name: Verify that maven artifact has no dependencies of type SNAPSHOT
        uses: jactor-rises/bidrag-actions/verify-mvn-dependencies@v2.0.1
      - name: build & test with maven
        run: mvn -B install

  git:
    needs: build
    if: github.ref == 'refs/heads/master'
    name: Modify git history
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn -B release:update-versions
      - run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout > .new-version
      - uses: jactor-rises/actions/git-commit@v4.0.3
        with:
          commit_message: "Bumped to new version: {}"
          commit_message_file: .new-version
          pattern: pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
