#  TODO: scheduled integration test workflow
#  integration:
#    name: integration tests
#    needs: ci
#    runs-on: ubuntu-latest
#    on:
#      schedule:
#        - cron: '* 5 * * *'

name: continious integration
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  ci-maven:
    runs-on: ubuntu-latest

    steps:
      - name: init
        uses: actions/checkout@v1
      - name: debug
        run: env
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: build & test with maven
        env:
          ARTIFACT: 'jactor-web'
          IMAGE: 'maven:3.6.2-jdk-13'
          M2_REPO: '.m2/repository'
        run: |
          docker run --rm --name "$ARTIFACT" \
            -v "$HOME/$M2_REPO":/root/.m2 \
            -v "$PWD":/usr/src/maven \
            -w /usr/src/maven "$IMAGE" mvn -B install
