name: continious integration
on:
  push:
    branches:
      - '**'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/jactor-persistence:REPLACE_WITH_SHORT_SHA

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build and test with maven, then create and publish docker image

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 13
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: env
      - uses: jactor-rises/actions/setup-maven@v1.0.0-jactor-rises
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: jactor-rises/actions/verify-mvn-dependencies@v1.0.0-jactor-rises
      - run: mvn -B install -e
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          IMAGE_WITH_SHORT_SHA=$(echo $IMAGE | sed "s/REPLACE_WITH_SHORT_SHA/$SHORT_SHA/")
          docker build --tag ${IMAGE_WITH_SHORT_SHA} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE_WITH_SHORT_SHA}

  git:
    needs: build
    if: github.ref == 'refs/heads/master'
    name: Modify git history
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1.1.3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn -B release:update-versions
      - run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout > .new-version
      - uses: jactor-rises/actions/git-commit@v1.0.0-jactor-rises
        with:
          commit_message: "Bumped to new version: {}"
          commit_message_file: .new-version
          pattern: pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
