name: continious integration on master
on:
  push:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: init
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: debug
        run: env
      - name: cache maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: verify that maven artifact has no dependencies of type SNAPSHOT
        uses: jactor-rises/actions/verify-mvn-dependencies@master
      - name: build & test with maven
        run: mvn -B install
      - name: prepare maven artifact for release
        if: github.ref == 'refs/heads/master'
        uses: jactor-rises/actions/release-prepare-mvn-artifact@master
        env:
          TAG_FILE_NAME: .tag-artifact
      - name: commit new version
        if: github.ref == 'refs/heads/master'
        uses: EndBug/add-and-commit@v2.3.0
        with:
          message: "Bumped to new version"
          path: "."
          pattern: "pom.xml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
