name: continuous integration
on:
  push:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build and test with maven

    steps:
      - run: env
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: jactor-rises/actions/setup-maven@v1.x-jactor-rises
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: navikt/bidrag-maven/verify-dependencies@v1.0.4
      - run: mvn -B install -e

  integration:
    runs-on: ubuntu-latest
    name: Integration tests of jactor-web <-> jactor-persistence

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: jactor-rises/actions/setup-maven@v1.x-jactor-rises
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: jactor-rises/jactor-persistence/run-docker@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE: docker.pkg.github.com/jactor-rises/jactor-persistence/jactor-persistence:latest
      - run: mvn test -e -Dtest=UserConsumerIntegrationTest

  git:
    needs: [build, integration]
    if: github.ref == 'refs/heads/main'
    name: Modify git history
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn -B release:update-versions
      - name: Next snapshot version
        id: snapshot
        run: echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      - uses: navikt/bidrag-git/commit@v3
        with:
          commit_message: "Bumped to new version: ${{ steps.snapshot.outputs.version }}"
          pattern: pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
