name: continious integration
on:
  push:
    branches:
      - '**'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/jactor-persistence:REPLACE_WITH_SHORT_SHA

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build and test with maven, then publish created docker image

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: debug
        run: env
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: verify that maven artifact has no dependencies of type SNAPSHOT
        uses: jactor-rises/bidrag-actions/verify-mvn-dependencies@v2.0.1
      - name: build & test with maven
        run: mvn -B install
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          IMAGE_WITH_SHORT_SHA=$(echo $IMAGE | sed "s/REPLACE_WITH_SHORT_SHA/$SHORT_SHA/")
          docker build --tag ${IMAGE_WITH_SHORT_SHA} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE_WITH_SHORT_SHA}

  git:
    needs: build
    if: github.ref == 'refs/heads/master'
    name: Modify git history
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: bump snapshot version
        run: mvn -B release:update-versions
      - name: commit new version
        uses: jactor-rises/bidrag-actions/tag-and-commit@v2.0.1
        with:
          commit_message: "Bumped to new version"
          pattern: "pom.xml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
