name: continious integration
on:
  push:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build and test with maven

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 13
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
          ${{ runner.os }}-maven-
      - run: env
      - uses: jactor-rises/bidrag-actions/verify-mvn-dependencies@v2.0.1
      - run: mvn -B install

  git:
    needs: build
    if: github.ref == 'refs/heads/master'
    name: Modify git history
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: bump snapshot version
        run: mvn -B release:update-versions
      - name: commit new version
        uses: jactor-rises/bidrag-actions/tag-and-commit@v2.0.1
        with:
          commit_message: "Bumped to new version"
          pattern: "pom.xml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
