name: continuous integration
on: push

env:
  IMAGE: ghcr.io/${{ github.repository }}:latest

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build, create, and then publish

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - run: ./gradlew build
      - name: Verify dependencies
        run: |
          COUNT=$(./gradlew -q dependencies | grep -c SNAPSHOT || true)

          echo "Found $COUNT SNAPSHOT dependencies"

          if [ "$COUNT" -gt 0 ]
          then
            >&2 echo ::error No SNAPSHOT dependencies allowed
            exit 1;
          fi
      - name: Build and publish docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker image build --tag ${IMAGE} .
          CONTAINER_ID=$(docker inspect --format="{{.Id}}" ${IMAGE})
          docker tag ${CONTAINER_ID} "ghcr.io/${GITHUB_REPOSITORY}:$(git rev-parse --short HEAD)"
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker image push ${IMAGE}

  cucumber:
    needs: build
    name: Integration tests with cucumber
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: jactor-rises/jactor-cucumber
          path: jactor-cucumber
      - uses: jactor-rises/jactor-persistence/run-docker@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: run cucumber tests
        run: cd jactor-cucumber && mvn test -P cucumber

  git:
    if: github.ref == 'refs/heads/main'
    name: Bump dev version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jactor-rises/actions/git-tag-snapshot@v2-git-tag-snapshot
