#  TODO: scheduled integration test workflow
#  integration:
#    name: integration tests
#    needs: ci
#    runs-on: ubuntu-latest
#    on:
#      schedule:
#        - cron: '* 5 * * *'

name: continious integration
on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - master

jobs:
  ci-maven:
    runs-on: ubuntu-latest

    steps:
      - name: init
        uses: actions/checkout@v1
      - name: build & test with maven
        runs: 'docker run -it --rm --name jactor-persistence -v $GITHUB_WORKSPACE/jactor-persistence:/usr/src/maven maven:3.6.2-jdk-12 mvn package'
