name: continuous integration
on:
  push:
    branches:
      - '**'

env:
  IMAGE: ghcr.io/${{ github.repository }}:latest

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build and test with maven, then create and publish docker image

    steps:
      - run: env
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: jactor-rises/actions/maven-setup@v2-maven-setup
        with:
          repositories: maven-central=https://repo.maven.apache.org/maven2,jactor-shared=https://maven.pkg.github.com/jactor-rises/jactor-shared
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: jactor-rises/actions/maven-verify-dependencies@v2-maven-verify-dependencies
      - run: mvn -B install -e
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker image build --tag ${IMAGE} .
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker image push ${IMAGE}

  cucumber:
    needs: build
    name: Integration tests with cucumber
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: jactor-rises/jactor-cucumber
          path: jactor-cucumber
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/jactor-cucumber/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: jactor-rises/jactor-persistence/run-docker@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: run cucumber tests
        run: cd jactor-cucumber && mvn test -P cucumber

  git:
    needs: cucumber
    if: github.ref == 'refs/heads/main'
    name: Bump dev version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jactor-rises/actions/git-tag-snapshot@v2-git-tag-snapshot
