name: build run docker
on:
  push:
    branches-ignore:
      - main

jobs:
  build-docker-run:
    runs-on: ubuntu-latest
    name: build actions with ncc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: npm i -g @zeit/ncc
      - name: Install run-docker
        uses: navikt/bidrag-node/build-with-ncc@v1
        with:
          artifact_folder: jactor-persistence/run-docker
      - name: Generate timestamp
        id: now
        run: echo ::set-output name=timestamp::$(date +"%Y-%m-%d:%T")
      - uses: navikt/bidrag-git/commit@v3
        with:
          commit_message: "${{ steps.now.outputs.timestamp }}: Build of docker-run action with npm and ncc"
          pattern: run-docker/.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
