name: verify pull request on jactor-persistence
on:
  pull_request:
    branches:
      - main
    paths:
      - 'persistence/**'

jobs:
  verify-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: --build-cache assemble
