name: Prepare deploy of maven artifact

on: [workflow_call]

jobs:

  deploy:
    runs-on: ubuntu-latest
    name:  Deploy maven artifact

    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest snapshot semantic version
        id: snapshot
        run: |
          git fetch --tags
          CURRENT_SEMVER=$(git tag --sort=-v:refname --list "[0-9].[0-9].[0-9]*[-snapshot]" | sed 's;-snapshot;;'| head -n 1)
          echo ::set-output name=semver::$CURRENT_SEMVER
      - name: Fetch latest changelog semantic version
        id: changelog
        run: |
          CURRENT_SEMVER=$(cat README.md | grep "[0-9]*\.[0-9]*\.[0-9]" | awk '{print $2}' | head -n 1)
          echo ::set-output name=semver::$CURRENT_SEMVER
      - name: Create new semantic version
        if: ${{ steps.snapshot.outputs.semver == steps.changelog.outputs.semver }}
        id: semver
        run: |
          workflow/scripts/new-semver.main.kts semver=$CURRENT_SNAPSHOT_VERSION
          echo ::set-output name=new::$(cat newSemVer)
        env:
          CURRENT_SNAPSHOT_VERSION: ${{ steps.snapshot.outputs.semver }}
          IS_DEBUG: true
      - name: Deploy when versions are equal
        if: ${{ steps.snapshot.outputs.semver == steps.changelog.outputs.semver }}
        uses: jactor-rises/jactor-shared/deploy-n-tag@v1
        with:
          release: ${{ steps.changelog.outputs.semver }}
          token: ${{ secrets.GITHUB_TOKEN }}
