name: tag jactor-modules/web
on:
  push:
    branches:
      - main
    paths:
      - 'web/**'

jobs:
  tag:
    name: Bump dev version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetch current semantic version
        id: current
        run: |
          git fetch --tags
          CURRENT_SEMVER=$(git tag --sort=-v:refname -l "*-web" | head -n 1)
          echo "semver=$CURRENT_SEMVER" >> $GITHUB_OUTPUT
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - run: ./gradlew :web:assemble
      - name: Fetch current major/minor release
        id: version
        run: |
          MAJOR_MINOR=$(./gradlew :web:properties | grep version: | grep SNAPSHOT | awk '{print $2}')
          echo "toPatch=$MAJOR_MINOR" >> $GITHUB_OUTPUT
      - name: Create new semantic version
        id: semver
        run: |
          .github/workflows/new-semver.main.kts majorMinor=${{ steps.version.outputs.toPatch }} semantic=${{ steps.current.outputs.semver }}
          echo "new=$(cat newSemVer)" >> $GITHUB_OUTPUT
      - name: Fetch github event metadata
        id: metadata
        run: |
          echo "email=$(jq .commits $GITHUB_EVENT_PATH | jq '.[].committer.email' | head -n 1)" >> $GITHUB_OUTPUT
          echo "name=$(jq .commits $GITHUB_EVENT_PATH | jq '.[].author.name' | head -n 1)" >> $GITHUB_OUTPUT
      - name: Tag new semantic version for web
        run: |
          git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email "${{ steps.metadata.outputs.email }}"
          git config --global user.name "${{ steps.metadata.outputs.name }}"
          git tag -a "${{ steps.semver.outputs.new }}-web" -m "New version tagged. Previous: ${{ steps.current.outputs.semver }}"
          git push --tags
        env:
          AUTHOR_EMAIL: ${{ steps.metadata.outputs.email }}
          AUTHOR_NAME: ${{ steps.metadata.outputs.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMANTIC_VERSION_CURRENT: ${{ steps.current.outputs.semver }}
          SEMANTIC_VERSION_NEW: ${{ steps.semver.outputs.new }}