name: tag jactor-modules/web
on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - 'shared/**'

jobs:
  tag:
    name: Bump dev version
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Increase this value as needed

    steps:
      - uses: actions/checkout@v2
      - name: Fetch current semantic version
        id: current
        run: |
          git fetch --tags
          CURRENT_SEMVER=$(git tag --sort=-v:refname -l "*-web" | head -n 1)
          echo "current semantic version tag: $CURRENT_SEMVER"
          NUMBERS=$(echo $CURRENT_SEMVER | sed 's/-.*//')
          echo "current semantic version version: $NUMBERS"
          echo "semver=$NUMBERS" >> $GITHUB_OUTPUT
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - run: ./gradlew :web:assemble
      - name: Fetch current major/minor release
        id: version
        run: |
          MAJOR_MINOR=$(./gradlew :web:properties | grep version: | grep SNAPSHOT | awk '{print $2}')
          echo "Project version guide: $MAJOR_MINOR"
          NUMBERS=$(echo $MAJOR_MINOR | sed 's/\.x-.*$//')
          echo "Major/minor version: $NUMBERS"
          echo "toPatch=$NUMBERS" >> $GITHUB_OUTPUT
      - name: Create new semantic version
        id: semver
        run: |
          NEW_SEM_VER=$(.github/workflows/new-semver.main.kts majorMinor=${{ steps.version.outputs.toPatch }} \
            currentSemVer=${{ steps.current.outputs.semver }})
          echo "new semantic version: $NEW_SEM_VER"
          echo "newSemVer=$NEW_SEM_VER" >> $GITHUB_OUTPUT
      - name: Fetch github event metadata
        id: metadata
        run: |
          echo "email=$(jq -r '.commits[0].committer.email' $GITHUB_EVENT_PATH)" >> $GITHUB_OUTPUT
          echo "name=$(jq -r '.commits[0].author.name' $GITHUB_EVENT_PATH)" >> $GITHUB_OUTPUT
      - name: Tag new snapshot version for web
        id: tag-web
        run: |
          git remote set-url origin https://${{ github.actor }}:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git config --global user.email "${{ steps.metadata.outputs.email }}"
          git config --global user.name "${{ steps.metadata.outputs.name }}"

          git tag -a "${{ steps.semver.outputs.newSemVer }}-web" \
            -m "New version tagged. Previous: ${{ steps.current.outputs.semver }}"
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
