name: tag jactor-modules/persistence
on:
  push:
    branches:
      - main
    paths:
      - 'persistence/**'

jobs:
  tag:
    name: Bump dev version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetch current semantic version
        id: current
        run: |
          git fetch --tags
          CURRENT_SEMVER=$(git tag --sort=-v:refname -l "*-persistence" | head -n 1)
          echo "semver=$CURRENT_SEMVER" >> $GITHUB_OUTPUT
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - run: ./gradlew :persistence:assemble
      - name: Fetch current major/minor release
        id: version
        run: |
          MAJOR_MINOR=$(./gradlew :persistence:properties | grep version: | grep SNAPSHOT | awk '{print $2}')
          echo "toPatch=$MAJOR_MINOR" >> $GITHUB_OUTPUT
      - name: Create new semantic version
        id: semver
        run: |
          .github/workflows/new-semver.main.kts majorMinor=${{ steps.version.outputs.toPatch }} semantic=${{ steps.current.outputs.semver }}
          echo "new=$(cat newSemVer)" >> $GITHUB_OUTPUT
      - name: Fetch github event metadata
        id: metadata
        run: |
          echo "email=$(jq .commits $GITHUB_EVENT_PATH | jq '.[].committer.email' | head -n 1)" >> $GITHUB_OUTPUT
          echo "name=$(jq .commits $GITHUB_EVENT_PATH | jq '.[].author.name' | head -n 1)" >> $GITHUB_OUTPUT
      - name: Tag new semantic version for persistence
        run: |
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git config --global user.email "${{ secrets.AUTHOR_EMAIL }}"
          git config --global user.name "${{ secrets.AUTHOR_NAME }}"
          git tag -a "${{ env.SEMANTIC_VERSION_NEW }}-persistence" -m "New version tagged. Previous: ${{ env.SEMANTIC_VERSION_CURRENT }}"
          git push --tags
        env:
          AUTHOR_EMAIL: ${{ secrets.AUTHOR_EMAIL }}
          AUTHOR_NAME: ${{ secrets.AUTHOR_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMANTIC_VERSION_CURRENT: ${{ steps.get_version.outputs.current }}
          SEMANTIC_VERSION_NEW: ${{ steps.get_version.outputs.new }}